src/Entity/Resume.php
<?php

namespace App\Entity;

use App\Repository\ResumeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ResumeRepository::class)
 */
class Resume
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lieu;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $subject;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $message;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $date_debut;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $date_fin;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getSubject(): ?string
    {
        return $this->subject;
    }

    public function setSubject(string $subject): self
    {
        $this->subject = $subject;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getDateDebut(): ?string
    {
        return $this->date_debut;
    }

    public function setDateDebut(string $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?string
    {
        return $this->date_fin;
    }

    public function setDateFin(string $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }
}

src/Form/ResumeType.php
<?php

namespace App\Form;

use App\Entity\Resume;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ResumeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('type')
            ->add('lieu')
            ->add('adresse')
            ->add('subject')
            ->add('message')
            ->add('date_debut')
            ->add('date_fin')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Resume::class,
        ]);
    }
}

src/Controller/ResumeController.php
<?php

namespace App\Controller;

use App\Entity\Resume;
use App\Form\ResumeType;
use App\Repository\ResumeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/resume")
 */
class ResumeController extends AbstractController
{
    /**
     * @Route("/", name="resume_index", methods={"GET"})
     */
    public function index(ResumeRepository $resumeRepository): Response
    {
        $formation = $resumeRepository->findBy(
            ['type' => 'formation']
        );
        $experience = $resumeRepository->findBy(
            ['type' => 'experience']
        );

        return $this->render('resume/index.html.twig', [
            'formation' => $formation,
            'experience' => $experience,
        ]);
    }

    /**
     * @Route("/new", name="resume_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $resume = new Resume();
        $form = $this->createForm(ResumeType::class, $resume);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($resume);
            $entityManager->flush();

            return $this->redirectToRoute('resume_index');
        }
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'User tried to access a page without having ROLE_ADMIN');
        return $this->render('resume/new.html.twig', [
            'resume' => $resume,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="resume_show", methods={"GET"})
     */
    public function show(Resume $resume): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'User tried to access a page without having ROLE_ADMIN');
        return $this->render('resume/show.html.twig', [
            'resume' => $resume,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="resume_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Resume $resume): Response
    {
        $form = $this->createForm(ResumeType::class, $resume);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('resume_index');
        }
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'User tried to access a page without having ROLE_ADMIN');
        return $this->render('resume/edit.html.twig', [
            'resume' => $resume,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="resume_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Resume $resume): Response
    {
        if ($this->isCsrfTokenValid('delete' . $resume->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($resume);
            $entityManager->flush();
        }
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'User tried to access a page without having ROLE_ADMIN');
        return $this->redirectToRoute('resume_index');
    }
}

templates/resume/_delete_form.html.twig
<form method="post" action="{{ path('resume_delete', {'id': resume.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ resume.id) }}">
    <button class="btn">Delete</button>
</form>

templates/resume/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/resume/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Resume
{% endblock %}

{% block body %}
	<main id="main">
		<h1>Edit Resume</h1>

		{{ include('resume/_form.html.twig', {'button_label': 'Update'}) }}

		<a href="{{ path('resume_index') }}">back to list</a>

		{{ include('resume/_delete_form.html.twig') }}
	</main>
{% endblock %}

templates/resume/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ResumeController!
{% endblock %}

{% block body %}
	<main id="main">
		<section id="resume" class="resume">
			<div class="container">

				<div class="section-title">
					<h2>Curriculum Vitae</h2>
				</div>

				<div class="row">
					<div class="col-lg-6" {# data-aos="fade-up" #}>

						<h3 class="resume-title">Formation</h3>
						{% for formations in formation %}
							<div class="resume-item">
								<h4>{{formations.name}}
									&amp; Graphic Design</h4>
								<h5>{{formations.datedebut}}
									-
									{{formations.datefin}}</h5>
								<p>
									<em>{{formations.lieu}},
										{{formations.adresse}}</em>
								</p>
								<p>{{formations.message}}</p>
								{% if is_granted('ROLE_ADMIN') %}
									<td>
										<a href="{{ path('resume_edit', {'id': formations.id}) }}">edit</a>
									</td>
								{% endif %}
							</div>
						{% endfor %}
					</div>
					<div class="col-lg-6" {# data-aos="fade-up" #} data-aos-delay="100">
						<h3 class="resume-title">Expérience professionel</h3>
						{% for experiences in experience %}
							<div class="resume-item">
								<h4>{{experiences.name}}
								</h4>
								<h5>{{experiences.datedebut}}
									-
									{{experiences.datefin}}</h5>
								<p>
									<em>{{experiences.lieu}},
										{{experiences.adresse}}</em>
								</p>
								<p>{{experiences.message}}</p>
								{% if is_granted('ROLE_ADMIN') %}
									<td>
										<a href="{{ path('resume_edit', {'id': experiences.id}) }}">edit</a>
									</td>
								{% endif %}
							</div>
						{% endfor %}
					</div>
					{% if is_granted('ROLE_ADMIN') %}
						<a href="{{ path('resume_new') }}">Create new</a>
					{% endif %}
				</div>
			</section>
		</main>

	{% endblock %}

templates/resume/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Resume
{% endblock %}

{% block body %}
	<main id="main">
		<h1>Create new Resume</h1>

		{{ include('resume/_form.html.twig') }}

		<a href="{{ path('resume_index') }}">back to list</a>
	</main>
{% endblock %}

templates/resume/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Resume{% endblock %}

{% block body %}
    <h1>Resume</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ resume.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ resume.name }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ resume.type }}</td>
            </tr>
            <tr>
                <th>Lieu</th>
                <td>{{ resume.lieu }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ resume.adresse }}</td>
            </tr>
            <tr>
                <th>Subject</th>
                <td>{{ resume.subject }}</td>
            </tr>
            <tr>
                <th>Message</th>
                <td>{{ resume.message }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ resume.dateDebut ? resume.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ resume.dateFin ? resume.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('resume_index') }}">back to list</a>

    <a href="{{ path('resume_edit', {'id': resume.id}) }}">edit</a>

    {{ include('resume/_delete_form.html.twig') }}
{% endblock %}